name: Build and deploy Node.js app to Azure Web App - IA-support-avo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      # If you use a lockfile (package-lock.json), prefer npm ci for reproducible builds
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      # Upload only what you actually need to deploy (adjust path for your app)
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
            !**/.git/**
            !**/.github/**
            !**/node_modules/**
            !**/tests/**
            !**/*.md

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C5F980E4AAAF40BDBFED89F581837A64 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3A0B7C14BC34497A83C7ABB351B28C87 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_60B4E065A76D4BE1888DEF190D36B70E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: IA-support-avo
          slot-name: Production
          package: .
